-- SELECT * FROM `clothes-shop`.categories 
-- where `clothes-shop`.categories.id in (select parent_id from categories);
-- SELECT * FROM `clothes-shop`.categories 
-- where `clothes-shop`.categories.id not in (select parent_id from categories);
-- SELECT * FROM `clothes-shop`.products
-- join `clothes-shop`.product_collection on `clothes-shop`.products.id=`clothes-shop`.product_collection.product_id
-- where `clothes-shop`.product_collection.collection_id=2;
-- select * from colors 
-- join product_color on colors.id = product_color.color_id
-- where product_color.product_id = 33;
-- select distinct sizes.* from sizes
-- join product_color_size on sizes.id = product_color_size.size_id
-- join product_color on product_color.id = product_color_size.product_color_id
-- join products on products.id = product_color.product_id
-- where products.id = 33;
-- select distinct sizes.* from sizes
-- join product_color_size on sizes.id = product_color_size.size_id
-- join product_color on product_color.id = product_color_size.product_color_id
-- join products on products.id = product_color.product_id
-- where products.id = 163;
-- select sizes.* from sizes
-- where sizes.id in(
-- select size_id from product_color_size
-- where product_color_size.product_color_id in 
-- (select product_color.id from product_color
-- join products on  products.id = product_color.product_id
-- where product_color.product_id=163));
-- update `clothes-shop`.products set `clothes-shop`.products.status = 1 where `clothes-shop`.products.id >0;
-- update `clothes-shop`.colors set `clothes-shop`.colors.status = 1 where `clothes-shop`.colors.id >0;
-- update `clothes-shop`.sizes set `clothes-shop`.sizes.status = 1 where `clothes-shop`.sizes.id >0;
-- update `clothes-shop`.categories set `clothes-shop`.categories.status = 1 where `clothes-shop`.categories.id >0; 